In [22]:
import numpy as np
import scipy.signal as ss

In [3]:
d = 3
a, b = np.mgrid[-d:d+1, -d:d+1]
print('a:', a, 'b:', b, sep='\n')

a:
[[-3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3]]
b:
[[-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]]


In [4]:
print(a+b)

[[-6 -5 -4 -3 -2 -1  0]
 [-5 -4 -3 -2 -1  0  1]
 [-4 -3 -2 -1  0  1  2]
 [-3 -2 -1  0  1  2  3]
 [-2 -1  0  1  2  3  4]
 [-1  0  1  2  3  4  5]
 [ 0  1  2  3  4  5  6]]


In [5]:
mask = np.abs(a+b) <= d
print(mask)

[[False False False  True  True  True  True]
 [False False  True  True  True  True  True]
 [False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True False]
 [ True  True  True  True  True False False]
 [ True  True  True  True False False False]]


In [6]:
print(mask * np.arange(11, 18))
g = np.arange(11, 18)
f = mask * g
print(f)
print(np.sum(f, axis=1) / np.sqrt(2 * d))
print((f / np.sqrt(2 * d)) @ np.ones(7, dtype=float))


[[ 0  0  0 14 15 16 17]
 [ 0  0 13 14 15 16 17]
 [ 0 12 13 14 15 16 17]
 [11 12 13 14 15 16 17]
 [11 12 13 14 15 16  0]
 [11 12 13 14 15  0  0]
 [11 12 13 14  0  0  0]]
[[ 0  0  0 14 15 16 17]
 [ 0  0 13 14 15 16 17]
 [ 0 12 13 14 15 16 17]
 [11 12 13 14 15 16 17]
 [11 12 13 14 15 16  0]
 [11 12 13 14 15  0  0]
 [11 12 13 14  0  0  0]]
[25.31139401 30.61862178 35.51760127 40.00833247 33.06811153 26.53613888
 20.41241452]
[25.31139401 30.61862178 35.51760127 40.00833247 33.06811153 26.53613888
 20.41241452]


In [25]:
true = (f @ g)  # / np.sqrt(2 * d)

# flip because formual is \sum_{k=-d}^d a_{k + \ell} a_k
# rather than a_{k - \ell}
test = np.flip(np.convolve(g, g, mode='same'))  # / np.sqrt(2 * d)

print(true)
print(test)
print(np.abs(true - test))

print(np.flip(ss.convolve(g, g, mode='same')))


[ 966 1135 1279 1400 1111  855  630]
[ 956 1115 1244 1344 1076  835  620]
[10 20 35 56 35 20 10]
[ 956 1115 1244 1344 1076  835  620]
