In [1]:
# install JAX using iPython magic command
%pip install --upgrade pip && pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

import jax
import jax.numpy as jnp

# jax.config.update("jax_enable_x64", True)

%env

  Using cached pip-22.1.1-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.1
    Uninstalling pip-22.1:
      Successfully uninstalled pip-22.1
Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
  Using cached jax-0.3.13-py3-none-any.whl
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.10%2Bcuda11.cudnn82-cp39-none-manylinux2014_x86_64.whl (128.0 MB)
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Note: you may need to restart the kernel to use updated packages.


{'PATH': '/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'HOSTNAME': 'jupyter-kcollins9-40ucmerced-2eedu',
 'NVARCH': 'x86_64',
 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.4 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=460,driver<461',
 'NV_CUDA_CUDART_VERSION': '11.4.148-1',
 'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-4',
 'CUDA_VERSION': '11.4.3',
 'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
 'NVIDIA_VISIBLE_DEVICES': 'GPU-607f71dd-569b-18dc-6f8f-4dbf7148ce43',
 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility',
 'NV_CUDA_LIB_VERSION': '11.4.3-1',
 'NV_NVTX_VERSION': '11.4.120-1',
 'NV_LIBNPP_VERSION': '11.4.0.110-1',
 'NV_LIBNPP_PACKAGE': 'libnpp-11-4=11.4.0.110-1',
 'NV_LIBCUSPARSE_VERSION': '11.6.0.120-1',
 'NV_LIBCUBLAS_PACKAGE_NAME': 'libcublas-11-4',
 'NV_LIBCUBLAS_VERSION': '11.6.5.2-1',
 'NV_LIBCUBLAS_PACKAGE': 'l

In [5]:
def sqfn(x):
    return x**2

jacosqfn = jax.jacobian(sqfn)

vec = jnp.array([1.0, 3.0, 7.0])

print('sqfn:', sqfn(vec))

print('gradsqfn:', jacosqfn(vec), sep='\n')

sqfn: [ 1.  9. 49.]
gradsqfn:
[[ 2.  0.  0.]
 [ 0.  6.  0.]
 [ 0.  0. 14.]]
